### ISSUE TITLE
an error(?) in README.md

### ISSUE THREAD

**Issue by ghost** [spencerwooo/firefox-overlay-scrollbar#2]
The code for Win10 in README.md is for Custom, and Custom is for Win10.

![2020-05-28 16_23_30-spencerwooofirefox-overlay-scrollbar_A_working_p](https://user-images.githubusercontent.com/32592043/83117421-a1360c80-a0ff-11ea-927e-dedf0a8b3726.png)

**Comment by spencerwooo** [comment]
Thanks, I'll fix this right away.
