### ISSUE TITLE
stopped working Firefox 85

### ISSUE THREAD

**Issue by abdulhkeemGit** [spencerwooo/firefox-overlay-scrollbar#4]
this deos not work on version 85

**Comment by Dr-Sauce** [comment]
It's not working for me too :(

**Comment by Dr-Sauce** [comment]
Just found out you have to delete the profile cache to solve the problem. (If that doesn't help, try installing it after deleting the cache.)
`about:profiles` → `Local Directory` - `Open Folder`

**Comment by abdulhkeemGit** [comment]
thanks man that really worked, you're awesome.
